import { Row, Col } from "antd";
import Head from "next/head";
import styles from "../styles/home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AFR-Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://iili.io/HrJvKMX.png" />
      </Head>

      <div>
        <Row>
          <Col span={10}></Col>
        </Row>
      </div>
    </div>
  );
}
export async function getStaticProps() {
  return { props: {} };
}
