import Head from "next/head";
import {
  Block1,
  Block2,
  Block3,
  Block4,
  Block5,
  BlockForm,
  Footer,
} from "../Components";

import styles from "../styles/home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AFR-Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://iili.io/HrJvKMX.png" />
      </Head>

      <div>
        <Block1></Block1>
        <Block2></Block2>
        <Block3></Block3>
        <Block4></Block4>
        <Block5></Block5>
        <BlockForm></BlockForm>
        <Footer></Footer>
      </div>
    </div>
  );
}
export async function getStaticProps() {
  return { props: {} };
}
